repo:
  url: https://github.com/rogerrum/k8s-gitops.git
  revision: main


applications:
  - name: argocd
    app-namespace: argocd
    namespace: argocd
    path: argocd
    manifest-paths: /argocd
    sync-wave: "-5"
    syncOptions:
      - ServerSideApply=true

  - name: infrastructure
    namespace: argocd
    path: infrastructure/
    manifest-paths: /infrastructure/templates;/infrastructure/Chart.yaml;/infrastructure/values.yaml
    sync-wave: "-4"

  - name: main
    namespace: argocd
    path: main/
    manifest-paths: /main/templates;/main/Chart.yaml;/main/values.yaml
    sync-wave: "-3"

  - name: root
    app-namespace: argocd
    namespace: argocd
    path: apps
    manifest-paths: /apps

  - name: system-upgrade
    namespace: system-upgrade
    path: system-upgrade/
    manifest-paths: /system-upgrade
    sync-wave: "-4"
    syncOptions:
      - CreateNamespace=true
