vernemq:
  image:
    repository: vernemq/vernemq
    tag: 1.11.0-alpine
  replicaCount: 1
  serviceMonitor:
    create: true
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.100.50
    ws:
      enabled: true
  statefulset:
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8888"
  additionalEnv:
    - name: DOCKER_VERNEMQ_ACCEPT_EULA
      value: "yes"
    - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
      value: "on"
    - name: DOCKER_VERNEMQ_PLUGINS__VMQ_BRIDGE
      value: "on"
    - name: DOCKER_VERNEMQ_VMQ_BRIDGE__TCP__BR0
      value: "192.168.1.241:2883"
    - name: DOCKER_VERNEMQ_VMQ_BRIDGE__TCP__BR0__TRY_PRIVATE
      value: "off"
    - name: DOCKER_VERNEMQ_VMQ_BRIDGE__TCP__BR0__TOPIC__1
      value: "event/metering/# in 0"
  podAntiAffinity: hard
